"""Device database describing the auxiliary pulser box "ASync TTL/DDS".

Designed to asynchronously control larger amounts of TTLs (GPIO's) & DDS's as
commanded by a master ARTIQ FPGA. It is similar in terms of hardware and flashing,
but has different wiring and thus a different device database.
"""
# ******************************************************************************
#                            Core Address
# ******************************************************************************
CORE_IP_ADDRESS = "169.254.70.100"

device_db = {
    # Aliases
    "dds0_switch"       : "sma0",
    "dds1_switch"       : "sma1",
    "dds2_switch"       : "sma2",
    "dds3_switch"       : "sma3",
    "dds4_switch"       : "sma4",
    "dds5_switch"       : "sma5",
    "dds6_switch"       : "sma6",
    "dds7_switch"       : "sma7",
    "dds8_switch"       : "sma8",
    "dds9_switch"       : "sma9",

    "sma9"              : "out4_0",

    "core": {
        "type": "local",
        "module": "artiq.coredevice.core",
        "class": "Core",
        "arguments": {
            "ref_period": 1e-9,
            "host": CORE_IP_ADDRESS,
        }
    },
    "core_log": {
        "type": "controller",
        "host": "::1",
        "port": 1068,
        "command": "aqctl_corelog -p {port} --bind {bind} " + CORE_IP_ADDRESS,
    },
    "core_cache": {
        "type": "local",
        "module": "artiq.coredevice.cache",
        "class": "CoreCache",
    },
    "core_dma": {
        "type": "local",
        "module": "artiq.coredevice.dma",
        "class": "CoreDMA"
    },
    "dac8568_1": {
        "type": "local",
        "module": "euriqabackend.coredevice.dac8568",
        "class": "DAC8568",
        "arguments": {
            "spi_device": "spi5",
            "chip_select": 1,
            "ldac_trigger": "load_dac_1",
        },
    },
    "out1_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 0},
        "comment": "This is a comment",
    },
    "out1_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 1},
    },
    "out1_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 2},
    },
    "out1_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 3},
    },
    "out1_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 4},
    },
    "out1_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 5},
    },
    "out1_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 6},
    },
    "out1_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 7},
    },
    "out2_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 8},
        "comment": "This is a comment",
    },
    "out2_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 9},
    },
    "out2_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 10},
    },
    "out2_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 11},
    },
    "out2_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 12},
    },
    "out2_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 13},
    },
    "out2_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 14},
    },
    "out2_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 15},
    },
    "out3_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 16},
        "comment": "This is a comment",
    },
    "out3_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 17},
    },
    "out3_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 18},
    },
    "out3_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 19},
    },
    "out3_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 20},
    },
    "out3_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 21},
    },
    "out3_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 22},
    },
    "out3_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 23},
    },
    "out4_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 24},
        "comment": "This is a comment",
    },
    "out4_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 25},
    },
    "out4_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 26},
    },
    "out4_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 27},
    },
    "out4_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 28},
    },
    "out4_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 29},
    },
    "out4_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 30},
    },
    "out4_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 31},
    },
    "in1_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 32},
    },
    "in1_0_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 32},
    },
    "in1_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 33},
    },
    "in1_1_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 33},
    },
    "in1_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 34},
    },
    "in1_2_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 34},
    },
    "in1_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 35},
    },
    "in1_3_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 35},
    },
    "in1_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 36},
    },
    "in1_4_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 36},
    },
    "in1_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 37},
    },
    "in1_5_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 37},
    },
    "in1_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 38},
    },
    "in1_6_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 38},
    },
    "in1_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 39},
    },
    "in1_7_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 39},
    },
    "in2_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 40},
    },
    "in2_0_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 40},
    },
    "in2_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 41},
    },
    "in2_1_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 41},
    },
    "in2_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 42},
    },
    "in2_2_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 42},
    },
    "in2_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 43},
    },
    "in2_3_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 43},
    },
    "in2_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 44},
    },
    "in2_4_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 44},
    },
    "in2_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 45},
    },
    "in2_5_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 45},
    },
    "in2_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 46},
    },
    "in2_6_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 46},
    },
    "in2_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 47},
    },
    "in2_7_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 47},
    },
    "in3_0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 48},
    },
    "in3_0_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 48},
    },
    "in3_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 49},
    },
    "in3_1_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 49},
    },
    "in3_2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 50},
    },
    "in3_2_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 50},
    },
    "in3_3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 51},
    },
    "in3_3_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 51},
    },
    "in3_4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 52},
    },
    "in3_4_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 52},
    },
    "in3_5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 53},
    },
    "in3_5_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 53},
    },
    "in3_6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 54},
    },
    "in3_6_edgecounter": {
        "type": "local",
        "module": "artiq.coredevice.edge_counter",
        "class": "EdgeCounter",
        "arguments": {"channel": 54},
    },
    "in3_7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLInOut",
        "arguments": {"channel": 55},
    },
    "led0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 56},
    },
    "led1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 57},
    },
    "oeb": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 58},
    },
    "sma0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 59},
    },
    "sma1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 60},
    },
    "sma2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 61},
    },
    "sma3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 62},
    },
    "sma4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 63},
    },
    "sma5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 64},
    },
    "sma6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 65},
    },
    "sma7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 66},
    },
    "sma8": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 67},
    },
    "io_update0": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 68},
    },
    "io_update1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 69},
    },
    "io_update2": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 70},
    },
    "io_update3": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 71},
    },
    "io_update4": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 72},
    },
    "io_update5": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 73},
    },
    "io_update6": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 74},
    },
    "io_update7": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 75},
    },
    "io_update8": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 76},
    },
    "io_update9": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 77},
    },
    "reset01": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 78},
    },
    "reset23": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 79},
    },
    "reset45": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 80},
    },
    "reset67": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 81},
    },
    "reset89": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 82},
    },
    "spi0": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 83},
    },
    "spi1": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 84},
    },
    "spi2": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 85},
    },
    "spi3": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 86},
    },
    "spi4": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 87},
    },
    # DAC 8568 8x DAC control lines
    "spi5": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
        "arguments": {"channel": 88},
    },
    "load_dac_1": {
        "type": "local",
        "module": "artiq.coredevice.ttl",
        "class": "TTLOut",
        "arguments": {"channel": 89},
    },
    "dds0": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi0",
            "io_update": "io_update0",
            "chip_select": 1,
        },
    },
    "dds1": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi0",
            "io_update": "io_update1",
            "chip_select": 2,
        },
    },
    "dds2": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi1",
            "io_update": "io_update2",
            "chip_select": 1,
        },
    },
    "dds3": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi1",
            "io_update": "io_update3",
            "chip_select": 2,
        },
    },
    "dds4": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi2",
            "io_update": "io_update4",
            "chip_select": 1,
        },
    },
    "dds5": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi2",
            "io_update": "io_update5",
            "chip_select": 2,
        },
    },
    "dds6": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi3",
            "io_update": "io_update6",
            "chip_select": 1,
        },
    },
    "dds7": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi3",
            "io_update": "io_update7",
            "chip_select": 2,
        },
    },
    "dds8": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi4",
            "io_update": "io_update8",
            "chip_select": 1,
        },
    },
    "dds9": {
        "type": "local",
        "module": "euriqabackend.coredevice.ad9912",
        "class": "AD9912",
        "arguments": {
            "spi_device": "spi4",
            "io_update": "io_update9",
            "chip_select": 2,
        },
    },

    "w_dds0": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds0",
            "dds_switch_device": "dds0_switch",
            "dds_reset_device": "reset01",
            "bus_group": 1,
        },
    },
    "w_dds1": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds1",
            "dds_switch_device": "dds1_switch",
            "dds_reset_device": "reset01",
            "bus_group": 2,
        },
    },
    "w_dds2": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds2",
            "dds_switch_device": "dds2_switch",
            "dds_reset_device": "reset23",
            "bus_group": 1,
        },
    },
    "w_dds3": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds3",
            "dds_switch_device": "dds3_switch",
            "dds_reset_device": "reset23",
            "bus_group": 2,
        },
    },
    "w_dds4": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds4",
            "dds_switch_device": "dds4_switch",
            "dds_reset_device": "reset45",
            "bus_group": 1,
        },
    },
    "w_dds5": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds5",
            "dds_switch_device": "dds5_switch",
            "dds_reset_device": "reset45",
            "bus_group": 2,
        },
    },
    "w_dds6": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds6",
            "dds_switch_device": "dds6_switch",
            "dds_reset_device": "reset67",
            "bus_group": 1,
        },
    },
    "w_dds7": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds7",
            "dds_switch_device": "dds7_switch",
            "dds_reset_device": "reset67",
            "bus_group": 2,
        },
    },
    "w_dds8": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds8",
            "dds_switch_device": "dds8_switch",
            "dds_reset_device": "reset89",
            "bus_group": 1,
        },
    },
    "w_dds9": {
        "type": "local",
        "module": "euriqabackend.devices.wrapped_core_hardware.mediator",
        "class": "WrappedDDSHardware",
        "arguments": {
            "dds_device": "dds9",
            "dds_switch_device": "dds9_switch",
            "dds_reset_device": "reset89",
            "bus_group": 2,
        },
    },
}
